spring.application.name=adoptme

# Dynamic Port assigned by Cloud Host (defaults to 8080 locally)
server.port=${PORT:8080}

# JWT Security
jwt.secret=${JWT_SECRET:4K8vB9qL2wXyZ7mN5pQ1rT3vY6uI0oP8sD4fG7hJ1kL=}
jwt.expiration-ms=604800000

# Hibernate & Database DDL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL / PostGIS DataSource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://ep-orange-paper-avv7bpqq.c-11.us-east-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:neondb_owner}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:npg_hmal79ACXdYz}
spring.datasource.driver-class-name=org.postgresql.Driver